### ISSUE TITLE
Adopt and implement integration tests

### ISSUE THREAD

**Issue by AxiomSamarth** [gardener/machine-controller-manager-provider-gcp#22]
**What would you like to be added**:
Adopt & implement implement integration tests based upon the new Golang based Integration tests suite from MCM.

**Why is this needed**:
This is needed so as to

have a generic integration test framework across providers
migrate the bash based integration tests to Golang based integration test

**Comment by himanshu-kun** [comment]
Post MCM Integration Test Improvements, this PR needs to run the test in the below scenarios as expected. Will update the chart as & when done.

Control Cluster | Target Cluster | MCM Image | MC Image | MachineClass | Action | Expected results | Actual Results 
--- | --- | --- | --- | --- | --- | --- | ---
Seed | Shoot | 0.40.0 | 0.5.0 | Not needed | Update MCM Deployment <br /> in shoot NS | Pass | 
Seed | Shoot | 0.40.0 | NA | Not needed | Update MCM Deployment <br /> in shoot NS | Pass | 
Seed | Shoot | NA | 0.5.0 | Not needed | Update MCM Deployment <br /> in shoot NS | Pass | 
Seed | Shoot | NA | NA | Not needed | Run MCM & MC locally <br /> & scaledown MCM <br />deployment to 0| Pass | 
Seed | Shoot | 0.40.0 | 0.5.0 | Provided | Use the provided Machine Class  | Pass | 
Shoot | Shoot | 0.40.0 | 0.5.0 | Provided | Deploy CRDs <br />& MCM in Control Cluster | Pass | 
Shoot | Shoot | 0.40.0 | NA | Provided | Deploy CRDs <br />& MCM in Control Cluster | Pass | 
Shoot | Shoot | NA | 0.5.0 | Provided | Deploy CRDs <br />& MCM in Control Cluster | Pass | 
Shoot | Shoot | NA | NA | Provided | Deploy CRDs in Control <br /> & Cluster Run MCM & MC locally | Pass | 
Shoot | Shoot | 0.40.0 | 0.5.0 | Not provided | Deploy CRDs <br />& MCM in Control Cluster | Fail |

**Comment by himanshu-kun** [comment]
All tests passed !
